image: redrock-fe
stages:
  - setup
  - deploy

prepare:
  stage: setup
  tags:
    - redrock-fe
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    - npm ci
  only:
    changes:
      - package-lock.json

production:
  stage: deploy
  when: manual
  tags:
    - redrock-fe
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - tar -cf dist.tar *
    - curl -F data=@dist.tar -X POST http://202.202.43.234/rrapi/deploy/node-service/$CI_PROJECT_NAME
